import Head from "next/head";
import { OWNER } from "../../constants/variables/owner";

const Meta = () => {
  return (
    <Head>
      <title>{OWNER.nickname}&apos;s portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Meta;
